pipeline {
    agent any

    environment {
        AWS_REGION      = 'ap-northeast-2'
        S3_BUCKET       = 'namg-codedeploy-artifacts-dev'   // 실제 버킷 이름
        ARTIFACT_PREFIX = 'namg-app'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend npm install') {
            steps {
                dir('backend') {
                    sh '''
                        if [ -f package-lock.json ]; then
                          npm ci
                        else
                          npm install
                        fi
                    '''
                }
            }
        }

        stage('Frontend build') {
            steps {
                dir('frontend') {
                    sh '''
                        if [ -f package-lock.json ]; then
                          npm ci
                        else
                          npm install
                        fi
                        npm run build
                    '''
                }
            }
        }

        stage('Package artifact') {
            steps {
                sh '''
                    rm -f artifact-*.zip || true

                    zip -r artifact-${ARTIFACT_PREFIX}-${BUILD_NUMBER}.zip \
                      backend \
                      frontend \
		      codedeploy-backend \                     
		      codedeploy-frontend \
		      jenkins \
		      -x "*/node_modules/*" ".git/*"
                '''
            }
        }

        stage('Upload to S3') {
            steps {
                sh '''
                    aws s3 cp artifact-${ARTIFACT_PREFIX}-${BUILD_NUMBER}.zip \
                      s3://${S3_BUCKET}/artifacts/artifact-${ARTIFACT_PREFIX}-${BUILD_NUMBER}.zip \
                      --region ${AWS_REGION}
                '''
            }
        }
    }
}

